import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#354a52",
        "primary-fixed-dim": "#60de85",
        "on-primary-fixed": "#00210b",
        tertiary: "#ffffff",
        "inverse-primary": "#006d33",
        "on-secondary-fixed": "#001f23",
        "on-surface-variant": "#bccabb",
        "error-container": "#93000a",
        "primary-fixed": "#7efc9f",
        "tertiary-fixed": "#cfe6f0",
        "secondary-fixed": "#acedf8",
        "on-tertiary": "#1e333b",
        secondary: "#91d1db",
        "surface-bright": "#38393a",
        "secondary-container": "#00545c",
        "on-background": "#e2e2e2",
        "surface-container-highest": "#333535",
        "surface-tint": "#60de85",
        "on-secondary": "#00363c",
        "on-tertiary-container": "#526870",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#007437",
        "primary-container": "#7efc9f",
        "on-primary": "#003918",
        background: "#081F26",
        surface: "#081F26",
        "surface-container-high": "#236871",
        outline: "#879486",
        "surface-dim": "#081F26",
        "tertiary-fixed-dim": "#b3cad4",
        error: "#ffb4ab",
        "outline-variant": "#236871",
        "surface-container-low": "#0b252d",
        "surface-container-lowest": "#041115",
        primary: "#7efc9f",
        "surface-container": "#112c33",
        "surface-variant": "#236871",
        "on-error": "#690005",
        "inverse-surface": "#FAFAFA",
        "tertiary-container": "#cfe6f0",
        "on-surface": "#FAFAFA",
        "secondary-fixed-dim": "#91d1db",
        "on-tertiary-fixed": "#071e25",
        "on-secondary-fixed-variant": "#004f57",
        "on-primary-fixed-variant": "#005225",
        "on-secondary-container": "#86c6d0",
        "inverse-on-surface": "#0B0B0B",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "2px",
        xl: "4px",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        "space-3xl": "6rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "gutter-desktop": "2.5rem",
        "margin-mobile": "1rem",
        margin: "2rem",
        "margin-desktop": "4rem",
      },
      fontFamily: {
        "body-sm": ["Manrope"],
        "body-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "label-sm": ["Space Grotesk"],
        "label-md": ["Space Grotesk"],
        "label-lg": ["Space Grotesk"],
        "headline-sm": ["Syne"],
        "headline-md": ["Syne"],
        "headline-lg": ["Syne"],
        "headline-lg-mobile": ["Syne"],
        "display-lg": ["Syne"],
        "display-lg-mobile": ["Syne"],
        "display-xl": ["Syne"],
        "display-xl-mobile": ["Syne"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.14em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-xl-mobile": ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};

export default config;
